name: call-block-logs

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: mkdir -p ~/.ssh/ && ssh-keyscan -H node.rugpullindex.com >> ~/.ssh/known_hosts
      - name: "Remove temporary artifacts"
        run: ssh root@node.rugpullindex.com "rm -rf data && rm -rf core/data/*"
      - name: "Clone neume-network/data on remote server"
        run: ssh root@node.rugpullindex.com "git clone git@github.com:neume-network/data.git"
      - name: "Generate a block logs crawl path"
        run: ssh root@node.rugpullindex.com "cd data/scripts && chmod +x * && ./generateBlockLogsCrawlPath > ../../core/crawl_path.mjs"
      - name: "Run partial block logs crawl"
        run: ssh root@node.rugpullindex.com "cd core && npm run dev"
      - name: "Remove potentially outdated remote"
        run: ssh root@node.rugpullindex.com "rm -rf data"
      - name: "And download remote again again"
        run: ssh root@node.rugpullindex.com "git clone git@github.com:neume-network/data.git"
      - name: "Copy results to local repository"
        run: ssh root@node.rugpullindex.com "cat core/data/call-block-logs-transformation >> data/results/call-block-logs-transformation"
      - name: "Upload to remote"
        run: ssh root@node.rugpullindex.com "cd data && git add results/call-block-logs-transformation && git commit -m 'Update from call-block-logs-transformation' && git push origin main"

