name: Index data

on:
  schedule: 
    - cron:  '0 13 * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Checkout neume-network/core
      uses: actions/checkout@v3
      with:
        repository: neume-network/core
        ref: main
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install neume-network/core dependencies
      run: npm ci
    - name: Run indexer
      run: npm run dev
      env:
        DATA_DIR: data
        RPC_HTTP_HOST: ${{ secrets.RPC_HTTP_HOST }}
        RPC_API_KEY: ""
        IPFS_HTTPS_GATEWAY: ${{ secrets.IPFS_HTTPS_GATEWAY }}
        IPFS_HTTPS_GATEWAY_KEY: ${{ secrets.IPFS_HTTPS_GATEWAY_KEY }}
        EXTRACTION_WORKER_CONCURRENCY: 50
    - name: Update neume-network/data
      uses: cpina/github-action-push-to-another-repository@main
      env:
        SSH_DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      with:
        source-directory: 'data'
        destination-github-username: 'neume-network'
        destination-repository-name: 'data'
        user-email: info@neume.network
        target-directory: results
        target-branch: main
