name: Index data

on:
  schedule:
    - cron: "0 13 * * *"
  workflow_dispatch:

jobs:
  call-block-logs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout neume-network/data
        uses: actions/checkout@v3
        with:
          path: neume-network-data
      - name: "Generate a block logs crawl path"
        run: |
          cd ./neume-network-data/scripts && \
          chmod +x * && \
          ./generateBlockLogsCrawlPath > ../steps/call-block-logs-generated.mjs && |
          cd ../..
      - name: Run a crawler step
        id: run_step
        uses: ./neume-network-data/.github/actions/run_step
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          rpc-http-host: ${{ secrets.RPC_HTTP_HOST }}
          ipfs-https-gateway-key: ${{ secrets.IPFS_HTTPS_GATEWAY_KEY }}
          current-step: 0

  logs-to-subgraph:
    runs-on: ubuntu-latest
    needs: call-block-logs
    steps:
      - name: Checkout neume-network/data
        uses: actions/checkout@v3
        with:
          path: neume-network-data
      - name: Run a crawler step
        id: run_step
        uses: ./neume-network-data/.github/actions/run_step
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          rpc-http-host: ${{ secrets.RPC_HTTP_HOST }}
          ipfs-https-gateway-key: ${{ secrets.IPFS_HTTPS_GATEWAY_KEY }}
          current-step: 1
          previous-step: 0

  soundxyz-call-tokenuri:
    runs-on: ubuntu-latest
    needs: logs-to-subgraph
    steps:
      - name: Checkout neume-network/data
        uses: actions/checkout@v3
        with:
          path: neume-network-data
      - name: Run a crawler step
        id: run_step
        uses: ./neume-network-data/.github/actions/run_step
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          rpc-http-host: ${{ secrets.RPC_HTTP_HOST }}
          ipfs-https-gateway-key: ${{ secrets.IPFS_HTTPS_GATEWAY_KEY }}
          current-step: 2
          previous-step: 1

  soundxyz-get-tokenuri:
    runs-on: ubuntu-latest
    needs: soundxyz-call-tokenuri
    steps:
      - name: Checkout neume-network/data
        uses: actions/checkout@v3
        with:
          path: neume-network-data
      - name: Run a crawler step
        id: run_step
        uses: ./neume-network-data/.github/actions/run_step
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          rpc-http-host: ${{ secrets.RPC_HTTP_HOST }}
          ipfs-https-gateway-key: ${{ secrets.IPFS_HTTPS_GATEWAY_KEY }}
          current-step: 3
          previous-step: 2

  zora-call-tokenuri:
    runs-on: ubuntu-latest
    needs: soundxyz-get-tokenuri
    steps:
      - name: Checkout neume-network/data
        uses: actions/checkout@v3
        with:
          path: neume-network-data
      - name: Run a crawler step
        id: run_step
        uses: ./neume-network-data/.github/actions/run_step
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          rpc-http-host: ${{ secrets.RPC_HTTP_HOST }}
          ipfs-https-gateway-key: ${{ secrets.IPFS_HTTPS_GATEWAY_KEY }}
          current-step: 4
          previous-step: 3

  zora-call-tokenmetadatauri:
    runs-on: ubuntu-latest
    needs: zora-call-tokenuri
    steps:
      - name: Checkout neume-network/data
        uses: actions/checkout@v3
        with:
          path: neume-network-data
      - name: Run a crawler step
        id: run_step
        uses: ./neume-network-data/.github/actions/run_step
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          rpc-http-host: ${{ secrets.RPC_HTTP_HOST }}
          ipfs-https-gateway-key: ${{ secrets.IPFS_HTTPS_GATEWAY_KEY }}
          current-step: 5
          previous-step: 4

  zora-get-tokenuri:
    runs-on: ubuntu-latest
    needs: zora-call-tokenmetadatauri
    steps:
      - name: Checkout neume-network/data
        uses: actions/checkout@v3
        with:
          path: neume-network-data
      - name: Run a crawler step
        id: run_step
        uses: ./neume-network-data/.github/actions/run_step
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          rpc-http-host: ${{ secrets.RPC_HTTP_HOST }}
          ipfs-https-gateway-key: ${{ secrets.IPFS_HTTPS_GATEWAY_KEY }}
          current-step: 6
          previous-step: 5

  music-os-accumulator:
    runs-on: ubuntu-latest
    needs: zora-get-tokenuri
    steps:
      - name: Checkout neume-network/data
        uses: actions/checkout@v3
        with:
          path: neume-network-data
      - name: Run a crawler step
        id: run_step
        uses: ./neume-network-data/.github/actions/run_step
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          rpc-http-host: ${{ secrets.RPC_HTTP_HOST }}
          ipfs-https-gateway-key: ${{ secrets.IPFS_HTTPS_GATEWAY_KEY }}
          current-step: 7
          previous-step: 6
          push-to-repo: true
