name: Index data

on:
  schedule: 
    - cron:  '0 13 * * *'
  workflow_dispatch:

jobs:
  web3subgraph:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout neume-network/data
        uses: actions/checkout@v3
        with:
          path: neume-network-data
      - name: Run a crawler step
        id: run_step
        uses: ./neume-network-data/.github/actions/run_step
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          rpc-http-host: ${{ secrets.RPC_HTTP_HOST }}
          ipfs-https-gateway-key: ${{ secrets.IPFS_HTTPS_GATEWAY_KEY }}
          current-step: 0
          push-to-repo: true
