name: Index data

on:
  schedule: 
    - cron:  '0 13 * * *'
  workflow_dispatch:

jobs:
  job_0:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout neume-network/data
        uses: actions/checkout@v3
        with:
          ref: dev
          path: neume-network-data
      - name: Run a crawler step
        id: run_step
        uses: ./neume-network-data/.github/actions/run_step
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          rpc-http-host: ${{ secrets.RPC_HTTP_HOST }}
          ipfs-https-gateway-key: ${{ secrets.IPFS_HTTPS_GATEWAY_KEY }}
          current-step: 0

  job_1:
    runs-on: ubuntu-latest
    needs: job_0
    steps:
      - name: Checkout neume-network/data
        uses: actions/checkout@v3
        with:
          ref: dev
          path: neume-network-data
      - name: Run a crawler step
        id: run_step
        uses: ./neume-network-data/.github/actions/run_step
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          rpc-http-host: ${{ secrets.RPC_HTTP_HOST }}
          ipfs-https-gateway-key: ${{ secrets.IPFS_HTTPS_GATEWAY_KEY }}
          current-step: 1
          previous-step: 0


  job_2:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - name: Checkout neume-network/data
        uses: actions/checkout@v3
        with:
          ref: dev
          path: neume-network-data
      - name: Run a crawler step
        id: run_step
        uses: ./neume-network-data/.github/actions/run_step
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          rpc-http-host: ${{ secrets.RPC_HTTP_HOST }}
          ipfs-https-gateway-key: ${{ secrets.IPFS_HTTPS_GATEWAY_KEY }}
          current-step: 2
          previous-step: 1
  
  job_3:
    runs-on: ubuntu-latest
    needs: job_2
    steps:
      - name: Checkout neume-network/data
        uses: actions/checkout@v3
        with:
          ref: dev
          path: neume-network-data
      - name: Run a crawler step
        id: run_step
        uses: ./neume-network-data/.github/actions/run_step
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          rpc-http-host: ${{ secrets.RPC_HTTP_HOST }}
          ipfs-https-gateway-key: ${{ secrets.IPFS_HTTPS_GATEWAY_KEY }}
          current-step: 3
          previous-step: 2
          
  job_4:
    runs-on: ubuntu-latest
    needs: job_3
    steps:
      - name: Checkout neume-network/data
        uses: actions/checkout@v3
        with:
          ref: dev
          path: neume-network-data
      - name: Run a crawler step
        id: run_step
        uses: ./neume-network-data/.github/actions/run_step
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          rpc-http-host: ${{ secrets.RPC_HTTP_HOST }}
          ipfs-https-gateway-key: ${{ secrets.IPFS_HTTPS_GATEWAY_KEY }}
          current-step: 4
          previous-step: 3
          
  job_5:
    runs-on: ubuntu-latest
    needs: job_4
    steps:
      - name: Checkout neume-network/data
        uses: actions/checkout@v3
        with:
          ref: dev
          path: neume-network-data
      - name: Run a crawler step
        id: run_step
        uses: ./neume-network-data/.github/actions/run_step
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          rpc-http-host: ${{ secrets.RPC_HTTP_HOST }}
          ipfs-https-gateway-key: ${{ secrets.IPFS_HTTPS_GATEWAY_KEY }}
          current-step: 5
          previous-step: 4

  job_6:
    runs-on: ubuntu-latest
    needs: job_5
    steps:
      - name: Checkout neume-network/data
        uses: actions/checkout@v3
        with:
          ref: dev
          path: neume-network-data
      - name: Run a crawler step
        id: run_step
        uses: ./neume-network-data/.github/actions/run_step
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          rpc-http-host: ${{ secrets.RPC_HTTP_HOST }}
          ipfs-https-gateway-key: ${{ secrets.IPFS_HTTPS_GATEWAY_KEY }}
          current-step: 6
          previous-step: 5
          push-to-repo: true
