name: Index data

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Checkout neume-network/core
      uses: actions/checkout@v3
      with:
        repository: neume-network/core
        ref: data-test-branch
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install neume-network/core dependencies
      run: npm ci
    - name: Run indexer
      run: npm run dev
      env:
        DATA_DIR: data
        RPC_HTTP_HOST: ${{ secrets.RPC_HTTP_HOST }}
        RPC_API_KEY: ""
        IPFS_HTTPS_GATEWAY: ${{ secrets.IPFS_HTTPS_GATEWAY }}
        IPFS_HTTPS_GATEWAY_KEY: ${{ secrets.IPFS_HTTPS_GATEWAY_KEY }}
        EXTRACTION_WORKER_CONCURRENCY: 100
    - run: ls data
    - run: cat data/web3subgraph-transformation
