name: Index data

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Checkout neume-network/data repository
      uses: actions/checkout@v3
      with:
        path: indexer-results
    - name: Checkout neume-network/core
      uses: actions/checkout@v3
      with:
        repository: neume-network/core
        ref: data-test-branch
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install neume-network/core dependencies
      run: npm ci
    - run: pwd
    - name: Delete old indexing result
      run: rm ../indexer-results/*
    - name: Run indexer
      run: npm run dev
      env:
        DATA_DIR: ../indexer-results
        RPC_HTTP_HOST: ${{ secrets.RPC_HTTP_HOST }}
        RPC_API_KEY: ""
        IPFS_HTTPS_GATEWAY: ${{ secrets.IPFS_HTTPS_GATEWAY }}
        IPFS_HTTPS_GATEWAY_KEY: ${{ secrets.IPFS_HTTPS_GATEWAY_KEY }}
        EXTRACTION_WORKER_CONCURRENCY: 100
    - name: Add data to repository
      uses: EndBug/add-and-commit@v9
      with:
        author_name: neume-network/data bot
        author_email: info@neume.network
        message: 'New results'
        add: ../indexer-results/web3subgraph-transformation
